# Generated by Django 6.0.7 on 2026-07-16 06:01

import studio.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('voice', models.CharField(default='af_heart', max_length=40)),
                ('language', models.CharField(default='a', max_length=8)),
                ('speed', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('format', models.CharField(default='wav', max_length=8)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=16)),
                ('audio_file', models.FileField(blank=True, upload_to=studio.models.audio_upload_path)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
