# Generated by Django 6.0.7 on 2026-07-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechgeneration',
            name='format',
            field=models.CharField(default='mp3', max_length=8),
        ),
        migrations.AlterField(
            model_name='speechgeneration',
            name='language',
            field=models.CharField(default='en-US', max_length=8),
        ),
        migrations.AlterField(
            model_name='speechgeneration',
            name='voice',
            field=models.CharField(default='en-US-AriaNeural', max_length=40),
        ),
    ]
