# Generated by Django 6.0.7 on 2026-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_speechgeneration_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechgeneration',
            name='format',
            field=models.CharField(default='wav', max_length=8),
        ),
        migrations.AlterField(
            model_name='speechgeneration',
            name='language',
            field=models.CharField(default='en_US', max_length=8),
        ),
        migrations.AlterField(
            model_name='speechgeneration',
            name='voice',
            field=models.CharField(default='en_US-ljspeech-medium', max_length=40),
        ),
    ]
